import dbConnect from '@/lib/mongodb';
import Venue from '@/models/Venue';
import { NextResponse } from 'next/server';

const SEED_VENUES = [
  {
    name: 'Anytime Fitness Vastrapur',
    address: 'A-205, Amrapali Lake View Tower, Opp. Hyatt International',
    city: 'Ahmedabad',
    description: 'Premium 24/7 fitness center featuring global access, advanced cardio, and strength training equipment.',
    pricePerHour: 150,
    rating: 4.6,
    reviewCount: 142,
    category: 'gym',
    bookingType: 'per_person',
    crowdLevel: 'moderate',
    hours: '24 Hours',
    phone: '079 4004 0000',
    image: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&q=80',
    amenities: ['AC', 'Parking', 'Showers', 'Lockers', 'WiFi'],
    equipment: ['Treadmill', 'Squat Rack', 'Dumbbells', 'Bench Press', 'Rowing Machine', 'Cable Machine'],
    priority: 0,
  },
  {
    name: 'Smash Arena Badminton',
    address: 'Near Shivalik Plaza, Prahlad Nagar',
    city: 'Ahmedabad',
    description: 'Professional indoor wooden flooring badminton courts. Matches standard tournament specifications.',
    pricePerHour: 250,
    rating: 4.8,
    reviewCount: 96,
    category: 'badminton',
    bookingType: 'per_court',
    crowdLevel: 'moderate',
    hours: '06:00 - 23:00',
    phone: '099988 55544',
    image: 'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=800&q=80',
    amenities: ['Parking', 'Showers', 'Equipment Rental', 'Refreshments Store'],
    equipment: ['Rackets', 'Nylon Shuttles', 'Feather Shuttles'],
    priority: 0,
  },
  {
    name: 'Kickoff Football Turf',
    address: 'Veera Desai Road, Andheri West',
    city: 'Mumbai',
    description: 'Premium 5-a-side and 7-a-side artificial football turf with high-quality floodlights for night play.',
    pricePerHour: 800,
    rating: 4.7,
    reviewCount: 184,
    category: 'football',
    bookingType: 'per_court',
    crowdLevel: 'moderate',
    hours: '06:00 - 02:00',
    phone: '022 6666 9999',
    image: 'https://images.unsplash.com/photo-1579952362874-86fd44d56af7?w=800&q=80',
    amenities: ['Showers', 'Change Rooms', 'Drinking Water', 'Spectator Seating'],
    equipment: ['Footballs', 'Bibs'],
    priority: 0,
  },
  {
    name: 'Aqua Splash Pool',
    address: 'HAL 2nd Stage, Indiranagar',
    city: 'Bengaluru',
    description: 'Temperature-controlled semi-olympic swimming pool with professional lifeguards and coaching slots available.',
    pricePerHour: 120,
    rating: 4.5,
    reviewCount: 78,
    category: 'swimming',
    bookingType: 'per_person',
    crowdLevel: 'low',
    hours: '06:00 - 21:00',
    phone: '080 5555 7777',
    image: 'https://images.unsplash.com/photo-1576013551627-0cc20b96c2a7?w=800&q=80',
    amenities: ['Lockers', 'Changing Rooms', 'Showers', 'Lifeguard Duty'],
    equipment: ['Kickboards', 'Pool Noodles'],
    priority: 0,
  },
  {
    name: 'Lords Cricket Academy Nets',
    address: 'Bapunagar Main Road',
    city: 'Ahmedabad',
    description: 'Professional outdoor cricket practice nets with bowling machine options. Perfect for team practice or solo drills.',
    pricePerHour: 300,
    rating: 4.4,
    reviewCount: 64,
    category: 'cricket',
    bookingType: 'per_court',
    crowdLevel: 'low',
    hours: '07:00 - 20:00',
    phone: '098250 54321',
    image: 'https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=800&q=80',
    amenities: ['Parking', 'Water Cooler', 'Bowling Machine (Chargeable)'],
    equipment: ['Cricket Bats', 'Leather Balls', 'Stumps', 'Leg Guards', 'Helmets'],
    priority: 0,
  },
  {
    name: 'NetPlay Tennis Court',
    address: 'One World Center, Lower Parel',
    city: 'Mumbai',
    description: 'Premium synthetic hard courts matching grand slam specifications. Night lights available for evening slots.',
    pricePerHour: 400,
    rating: 4.8,
    reviewCount: 110,
    category: 'tennis',
    bookingType: 'per_court',
    crowdLevel: 'low',
    hours: '06:00 - 22:00',
    phone: '022 4004 8888',
    image: 'https://images.unsplash.com/photo-1595435934249-5df7ed86e1c0?w=800&q=80',
    amenities: ['AC Lounge', 'Parking', 'Showers', 'Equipment Rental'],
    equipment: ['Tennis Rackets', 'Balls'],
    priority: 0,
  },
  {
    name: 'cult.fit Indiranagar',
    address: '1st Floor, Above Ritu Kumar, Indiranagar Double Rd, HAL 2nd Stage',
    city: 'Bengaluru',
    description: 'High-energy group workouts including Boxing, HRX, S&C, and Yoga in a state-of-the-art facility.',
    pricePerHour: 250,
    rating: 4.8,
    reviewCount: 890,
    category: 'gym',
    bookingType: 'per_person',
    crowdLevel: 'high',
    hours: '06:00 - 22:00',
    phone: '080 4444 3333',
    image: 'https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?w=800&q=80',
    amenities: ['AC', 'Showers', 'Lockers', 'Smart Check-in'],
    equipment: ['Dumbbells', 'Kettlebells', 'Boxing Bags', 'TRX', 'Rowing Machine'],
    priority: 0,
  },
  {
    name: 'Gold\'s Venue Lower Parel',
    address: 'One World Center, A-2 Tower 1, 3rd Floor, Lower Parel',
    city: 'Mumbai',
    description: 'A globally recognized brand offering professional training programs and comprehensive fitness equipment.',
    pricePerHour: 200,
    rating: 4.5,
    reviewCount: 450,
    category: 'gym',
    bookingType: 'per_person',
    crowdLevel: 'high',
    hours: '06:00 - 22:00',
    phone: '022 4004 5555',
    image: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=800&q=80',
    amenities: ['AC', 'Parking', 'Showers', 'Lockers'],
    equipment: ['Treadmill', 'Elliptical', 'Smith Machine', 'Dumbbells', 'Bench Press'],
    priority: 0,
  }
];

export async function POST() {
  try {
    await dbConnect();
    await Venue.deleteMany({}); // Clear existing venues to avoid mixed schema issues
    const venues = await Venue.insertMany(SEED_VENUES);
    return NextResponse.json({ message: `Seeded ${venues.length} venues`, venues });
  } catch (error) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
